name: dask_workshop
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh=2.0  # Pinned until distributed 2.19 release due to breaking change
  - dask=2.30.0
  - dask-ml
  - jupyterlab=2.2.6
  - ipykernel
  - ipywidgets
  - nodejs
  - tornado
  - numba
  - numpy
  - pip
  - pandas
  - python-graphviz
  - scikit-learn
  - nbserverproxy
  - requests
  - pip:
    - dask_labextension
    - dask-xgboost==0.1.11
